### ISSUE TITLE
SurvivalPlusFabric 0.1.7 crashes on 1.19.2, 0.1.6g does not

### ISSUE THREAD

**Issue by ValeTheVioletMote** [coolsimulations/SurvivalPlus#16]
```
[:] ---- Minecraft Crash Report ----
[:] // Uh... Did I do that?
[:] 
[:] Time: 2023-01-03 10:48:14
[:] Description: Initializing game
[:] 
[:] java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'survivalplus'!
[:] 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
[:] 	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
[:] 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
[:] 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
[:] 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
[:] 	at net.minecraft.class_310.<init>(class_310.java:459)
[:] 	at net.minecraft.client.main.Main.method_44604(Main.java:205)
[:] 	at net.minecraft.client.main.Main.main(Main.java:51)
[:] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
[:] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[:] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[:] Caused by: java.lang.IllegalAccessError: class net.coolsimulations.SurvivalPlus.core.SurvivalPlusClient tried to access private method 'void net.minecraft.class_5616.method_32144(net.minecraft.class_2591, net.minecraft.class_5614)' (net.coolsimulations.SurvivalPlus.core.SurvivalPlusClient and net.minecraft.class_5616 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @6cc7b4de)
[:] 	at net.coolsimulations.SurvivalPlus.core.SurvivalPlusClient.onInitializeClient(SurvivalPlusClient.java:59)
[:] 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
[:] 	... 8 more
[:] 
[:] 
[:] A detailed walkthrough of the error, its code path and all known details is as follows:
[:] ---------------------------------------------------------------------------------------
[:] 
[:] -- Head --
[:] Thread: Render thread
[:] Stacktrace:
[:] 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
[:] 	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
[:] 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
[:] 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
[:] 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
[:] 	at net.minecraft.class_310.<init>(class_310.java:459)
[:] 
[:] -- Initialization --
[:] Details:
[:] 	Modules: 
[:] Stacktrace:
[:] 	at net.minecraft.client.main.Main.method_44604(Main.java:205)
[:] 	at net.minecraft.client.main.Main.main(Main.java:51)
[:] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
[:] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[:] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

```

**Comment by coolsimulations** [comment]
Are you using the [1.19.3 version of 0.1.7](https://www.curseforge.com/minecraft/mc-mods/survivalplus-fabric/files/4278428) or the [1.19.2 version](https://www.curseforge.com/minecraft/mc-mods/survivalplus-fabric/files/4278415)? The 1.19.3 version will not work on 1.19.2.

**Comment by ValeTheVioletMote** [comment]
> Are you using the 1.19.3 version of 0.1.7 or the 1.19.2 version?

The 1.19.2 version. `SurvivalPlus-Fabric-1.19.2-0.1.7.jar`

**Comment by coolsimulations** [comment]
I'm not getting this crash. I'm using Fabric Loader 0.14.12 and Fabric API 0.71.0+1.19.2. Try again on a fresh install or send through the full crash log.

**Comment by ValeTheVioletMote** [comment]
My Fabric API is 0.68.0+1.19.2. I'll update that and see what happens.

**Comment by ValeTheVioletMote** [comment]
Updating the Fabric API to 0.71.0+1.19.2 fixed the problem. Thanks king!
